/* automatically generated by rust-bindgen 0.63.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nvlist {
    _unused: [u8; 0],
}
pub type nvlist_t = nvlist;
extern "C" {
    pub fn cap_channel_flags(chan: *const cap_channel_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_init() -> *mut cap_channel_t;
}
extern "C" {
    pub fn cap_service_open(
        chan: *const cap_channel_t,
        name: *const ::std::os::raw::c_char,
    ) -> *mut cap_channel_t;
}
extern "C" {
    pub fn cap_service_limit(
        chan: *const cap_channel_t,
        names: *const *const ::std::os::raw::c_char,
        nnames: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_wrap(
        sock: ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
    ) -> *mut cap_channel_t;
}
extern "C" {
    pub fn cap_unwrap(
        chan: *mut cap_channel_t,
        flags: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_clone(chan: *const cap_channel_t) -> *mut cap_channel_t;
}
extern "C" {
    pub fn cap_close(chan: *mut cap_channel_t);
}
extern "C" {
    pub fn cap_sock(chan: *const cap_channel_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_limit_set(
        chan: *const cap_channel_t,
        limits: *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_limit_get(
        chan: *const cap_channel_t,
        limitsp: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_send_nvlist(
        chan: *const cap_channel_t,
        nvl: *const nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_recv_nvlist(chan: *const cap_channel_t) -> *mut nvlist_t;
}
extern "C" {
    pub fn cap_xfer_nvlist(chan: *const cap_channel_t, nvl: *mut nvlist_t) -> *mut nvlist_t;
}
extern "C" {
    pub fn cap_getgrent(chan: *mut cap_channel_t) -> *mut group;
}
extern "C" {
    pub fn cap_getgrnam(
        chan: *mut cap_channel_t,
        name: *const ::std::os::raw::c_char,
    ) -> *mut group;
}
extern "C" {
    pub fn cap_getgrgid(chan: *mut cap_channel_t, gid: gid_t) -> *mut group;
}
extern "C" {
    pub fn cap_getgrent_r(
        chan: *mut cap_channel_t,
        grp: *mut group,
        buffer: *mut ::std::os::raw::c_char,
        bufsize: usize,
        result: *mut *mut group,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_getgrnam_r(
        chan: *mut cap_channel_t,
        name: *const ::std::os::raw::c_char,
        grp: *mut group,
        buffer: *mut ::std::os::raw::c_char,
        bufsize: usize,
        result: *mut *mut group,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_getgrgid_r(
        chan: *mut cap_channel_t,
        gid: gid_t,
        grp: *mut group,
        buffer: *mut ::std::os::raw::c_char,
        bufsize: usize,
        result: *mut *mut group,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_setgroupent(
        chan: *mut cap_channel_t,
        stayopen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_setgrent(chan: *mut cap_channel_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_endgrent(chan: *mut cap_channel_t);
}
extern "C" {
    pub fn cap_grp_limit_cmds(
        chan: *mut cap_channel_t,
        cmds: *const *const ::std::os::raw::c_char,
        ncmds: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_grp_limit_fields(
        chan: *mut cap_channel_t,
        fields: *const *const ::std::os::raw::c_char,
        nfields: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_grp_limit_groups(
        chan: *mut cap_channel_t,
        names: *const *const ::std::os::raw::c_char,
        nnames: usize,
        gids: *const gid_t,
        ngids: usize,
    ) -> ::std::os::raw::c_int;
}
