[package]
name = "cap_grp-sys"
version = "0.1.0"
edition = "2021"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MPL-2.0"
repository = "https://github.com/dlrobertson/capsicum-rs"
rust-version = "1.62"
description = """
FFI bindings for FreeBSD's libcasper
"""
keywords = ["sandbox", "FreeBSD", "capsicum"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-sys = { path = "../casper-sys" }
libc = { version = "0.2.138", features = [ "extra_traits" ] }
